### ISSUE TITLE
Mario won't spawn and the HUD and other G64 entities are broken

### ISSUE THREAD

**Issue by ExtCan** [ckosmic/g64#59]
I'm not entirely sure how to explain it so here's an image of the game and console

I have no addons installed and I'm using the GitHub version of the mod rather than the workshop
I'm not entirely sure how to explain it so here's an image of the game and console

![Screenshot 2022-07-23 165746](https://user-images.githubusercontent.com/60326708/180613061-a660c521-7df0-4c3b-96cf-1577fb3638b6.png)
![Screenshot 2022-07-23 165826](https://user-images.githubusercontent.com/60326708/180613063-90fe602a-4914-4306-b022-f142d292e70f.png)

**Comment by ExtCan** [comment]
I also have completely reinstalled Gmod and this still occurs

**Comment by ckosmic** [comment]
If you use the GitHub version you'll also have to manually build libsm64 and the G64 binary module since those are updated alongside the workshop addon and require the latest versions of each other to work.
If you don't want to deal with the pain of getting that set up, downloading the addon from the workshop is your best bet.
